package com.rgprn.m4puedeaprobar;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class puedeAprobarOD implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String tipoPrestacion;
	private java.lang.String tipoAporte;
	private java.lang.String aprobador;
	private java.lang.Double topeMonto;
	private java.lang.Integer tiempo;

	public puedeAprobarOD() {
	}

	public java.lang.String getTipoPrestacion() {
		return this.tipoPrestacion;
	}

	public void setTipoPrestacion(java.lang.String tipoPrestacion) {
		this.tipoPrestacion = tipoPrestacion;
	}

	public java.lang.String getTipoAporte() {
		return this.tipoAporte;
	}

	public void setTipoAporte(java.lang.String tipoAporte) {
		this.tipoAporte = tipoAporte;
	}

	public java.lang.String getAprobador() {
		return this.aprobador;
	}

	public void setAprobador(java.lang.String aprobador) {
		this.aprobador = aprobador;
	}

	public java.lang.Double getTopeMonto() {
		return this.topeMonto;
	}

	public void setTopeMonto(java.lang.Double topeMonto) {
		this.topeMonto = topeMonto;
	}

	public java.lang.Integer getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(java.lang.Integer tiempo) {
		this.tiempo = tiempo;
	}

	public puedeAprobarOD(java.lang.String tipoPrestacion,
			java.lang.String tipoAporte, java.lang.String aprobador,
			java.lang.Double topeMonto, java.lang.Integer tiempo) {
		this.tipoPrestacion = tipoPrestacion;
		this.tipoAporte = tipoAporte;
		this.aprobador = aprobador;
		this.topeMonto = topeMonto;
		this.tiempo = tiempo;
	}

}